package com.cnweak.rebash.fileftp;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.HashMap;
import java.util.Map;
import java.util.Properties;
public final class MimeUtils {
	private Map<String, String> map = new HashMap<String, String>(); 
	
	public Integer getFileMime(String filename){
		int poindex = filename.lastIndexOf(".");
		int fileok = 0;
		if (poindex > 0 ){
			String filepoint = filename.substring(poindex+1,filename.length());//截取尾部
			addMime();
			String fileType  = map.get(filepoint);  //获得类型
			if(fileType != null){
				String filesub = fileType.substring(0, fileType.indexOf("/"));//取类型前部分
				System.out.println(filesub);
				switch (filesub) {
						//0未知，1文本，2程序，3图片，4视频，5音频
						//6  包，7脚本
					case "text":
						fileok = 1;
						break;
					case "video":
						fileok = 4;
						break;
					case "image":
						fileok = 3;
						break;
					case "audio":
						fileok = 5;
						break;	
					case "application":
						fileok = 2;
						break;
					case "pack":
						fileok = 6;
						break;		
					case "script":
						fileok = 7;
						break;
				}
			}
		}
		return fileok;
	}
	
	
	
	
	private void addMimepPinnt(String one ,String two){
				map.put(two,one);
	}
    private void addMime() {
		addMimepPinnt("application/andrew-inset", "ez");
        addMimepPinnt("application/dsptype", "tsp");
        addMimepPinnt("application/futuresplash", "spl");
        addMimepPinnt("application/hta", "hta");
        addMimepPinnt("application/mac-binhex40", "hqx");
        addMimepPinnt("application/mac-compactpro", "cpt");
        addMimepPinnt("application/mathematica", "nb");
        addMimepPinnt("application/msaccess", "mdb");
        addMimepPinnt("application/oda", "oda");
        addMimepPinnt("application/ogg", "ogg");
        addMimepPinnt("application/pdf", "pdf");
        addMimepPinnt("application/pgp-keys", "key");
        addMimepPinnt("application/pgp-signature", "pgp");
        addMimepPinnt("application/pics-rules", "prf");
        addMimepPinnt("application/rar", "rar");
        addMimepPinnt("application/rdf+xml", "rdf");
        addMimepPinnt("application/rss+xml", "rss");
        //addMimepPinnt("application/zip", "zip");
        //addMimepPinnt("application/vnd.android.package-archive", "apk");
        addMimepPinnt("application/vnd.cinderella", "cdy");
        addMimepPinnt("application/vnd.ms-pki.stl", "stl");
        addMimepPinnt("application/vnd.oasis.opendocument.database", "odb");
        addMimepPinnt("application/vnd.oasis.opendocument.formula", "odf");
        addMimepPinnt("application/vnd.oasis.opendocument.graphics", "odg");
        addMimepPinnt("application/vnd.oasis.opendocument.graphics-template", "otg");
        addMimepPinnt("application/vnd.oasis.opendocument.image", "odi");
        addMimepPinnt("application/vnd.oasis.opendocument.spreadsheet", "ods");
        addMimepPinnt("application/vnd.oasis.opendocument.spreadsheet-template", "ots");
        addMimepPinnt("application/vnd.oasis.opendocument.text", "odt");
        addMimepPinnt("application/vnd.oasis.opendocument.text-master", "odm");
        addMimepPinnt("application/vnd.oasis.opendocument.text-template", "ott");
        addMimepPinnt("application/vnd.oasis.opendocument.text-web", "oth");
        addMimepPinnt("application/vnd.google-earth.kml+xml", "kml");
        addMimepPinnt("application/vnd.google-earth.kmz", "kmz");
        addMimepPinnt("application/msword", "doc");
        addMimepPinnt("application/msword", "dot");
        addMimepPinnt("application/vnd.openxmlformats-officedocument.wordprocessingml.document", "docx");
        addMimepPinnt("application/vnd.openxmlformats-officedocument.wordprocessingml.template", "dotx");
        addMimepPinnt("application/vnd.ms-excel", "xls");
        addMimepPinnt("application/vnd.ms-excel", "xlt");
        addMimepPinnt("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "xlsx");
        addMimepPinnt("application/vnd.openxmlformats-officedocument.spreadsheetml.template", "xltx");
        addMimepPinnt("application/vnd.ms-powerpoint", "ppt");
        addMimepPinnt("application/vnd.ms-powerpoint", "pot");
        addMimepPinnt("application/vnd.ms-powerpoint", "pps");
        addMimepPinnt("application/vnd.openxmlformats-officedocument.presentationml.presentation", "pptx");
        addMimepPinnt("application/vnd.openxmlformats-officedocument.presentationml.template", "potx");
        addMimepPinnt("application/vnd.openxmlformats-officedocument.presentationml.slideshow", "ppsx");
        addMimepPinnt("application/vnd.rim.cod", "cod");
        addMimepPinnt("application/vnd.smaf", "mmf");
        addMimepPinnt("application/vnd.stardivision.calc", "sdc");
        addMimepPinnt("application/vnd.stardivision.draw", "sda");
        addMimepPinnt("application/vnd.stardivision.impress", "sdd");
        addMimepPinnt("application/vnd.stardivision.impress", "sdp");
        addMimepPinnt("application/vnd.stardivision.math", "smf");
        addMimepPinnt("application/vnd.stardivision.writer", "sdw");
        addMimepPinnt("application/vnd.stardivision.writer", "vor");
        addMimepPinnt("application/vnd.stardivision.writer-global", "sgl");
        addMimepPinnt("application/vnd.sun.xml.calc", "sxc");
        addMimepPinnt("application/vnd.sun.xml.calc.template", "stc");
        addMimepPinnt("application/vnd.sun.xml.draw", "sxd");
        addMimepPinnt("application/vnd.sun.xml.draw.template", "std");
        addMimepPinnt("application/vnd.sun.xml.impress", "sxi");
        addMimepPinnt("application/vnd.sun.xml.impress.template", "sti");
        addMimepPinnt("application/vnd.sun.xml.math", "sxm");
        addMimepPinnt("application/vnd.sun.xml.writer", "sxw");
        addMimepPinnt("application/vnd.sun.xml.writer.global", "sxg");
        addMimepPinnt("application/vnd.sun.xml.writer.template", "stw");
        addMimepPinnt("application/vnd.visio", "vsd");
        addMimepPinnt("application/x-abiword", "abw");
        addMimepPinnt("application/x-apple-diskimage", "dmg");
        addMimepPinnt("application/x-bcpio", "bcpio");
        addMimepPinnt("application/x-bittorrent", "torrent");
        addMimepPinnt("application/x-cdf", "cdf");
        addMimepPinnt("application/x-cdlink", "vcd");
        addMimepPinnt("application/x-chess-pgn", "pgn");
        addMimepPinnt("application/x-cpio", "cpio");
        addMimepPinnt("application/x-debian-package", "deb");
        addMimepPinnt("application/x-debian-package", "udeb");
        addMimepPinnt("application/x-director", "dcr");
        addMimepPinnt("application/x-director", "dir");
        addMimepPinnt("application/x-director", "dxr");
        addMimepPinnt("application/x-dms", "dms");
        addMimepPinnt("application/x-doom", "wad");
        addMimepPinnt("application/x-dvi", "dvi");
        addMimepPinnt("application/x-flac", "flac");
        addMimepPinnt("application/x-font", "pfa");
        addMimepPinnt("application/x-font", "pfb");
        addMimepPinnt("application/x-font", "gsf");
        addMimepPinnt("application/x-font", "pcf");
        addMimepPinnt("application/x-font", "pcf.Z");
        addMimepPinnt("application/x-freemind", "mm");
        addMimepPinnt("application/x-futuresplash", "spl");
        addMimepPinnt("application/x-gnumeric", "gnumeric");
        addMimepPinnt("application/x-go-sgf", "sgf");
        addMimepPinnt("application/x-graphing-calculator", "gcf");
        //addMimepPinnt("application/x-gtar", "gtar");
        //addMimepPinnt("application/x-gtar", "tgz");
        //addMimepPinnt("application/x-gtar", "taz");
        addMimepPinnt("application/x-hdf", "hdf");
        addMimepPinnt("application/x-ica", "ica");
        addMimepPinnt("application/x-internet-signup", "ins");
        addMimepPinnt("application/x-internet-signup", "isp");
        addMimepPinnt("application/x-iphone", "iii");
        addMimepPinnt("application/x-iso9660-image", "iso");
        addMimepPinnt("application/x-jmol", "jmz");
        addMimepPinnt("application/x-kchart", "chrt");
        addMimepPinnt("application/x-killustrator", "kil");
        addMimepPinnt("application/x-koan", "skp");
        addMimepPinnt("application/x-koan", "skd");
        addMimepPinnt("application/x-koan", "skt");
        addMimepPinnt("application/x-koan", "skm");
        addMimepPinnt("application/x-kpresenter", "kpr");
        addMimepPinnt("application/x-kpresenter", "kpt");
        addMimepPinnt("application/x-kspread", "ksp");
        addMimepPinnt("application/x-kword", "kwd");
        addMimepPinnt("application/x-kword", "kwt");
        addMimepPinnt("application/x-latex", "latex");
        addMimepPinnt("application/x-lha", "lha");
        addMimepPinnt("application/x-lzh", "lzh");
        addMimepPinnt("application/x-lzx", "lzx");
        addMimepPinnt("application/x-maker", "frm");
        addMimepPinnt("application/x-maker", "maker");
        addMimepPinnt("application/x-maker", "frame");
        addMimepPinnt("application/x-maker", "fb");
        addMimepPinnt("application/x-maker", "book");
        addMimepPinnt("application/x-maker", "fbdoc");
        addMimepPinnt("application/x-mif", "mif");
        addMimepPinnt("application/x-ms-wmd", "wmd");
        addMimepPinnt("application/x-ms-wmz", "wmz");
        addMimepPinnt("application/x-msi", "msi");
        //addMimepPinnt("application/x-ns-proxy-autoconfig", "pac");
        addMimepPinnt("application/x-nwc", "nwc");
        addMimepPinnt("application/x-object", "o");
        addMimepPinnt("application/x-oz-application", "oza");
        addMimepPinnt("application/x-pkcs12", "p12");
        addMimepPinnt("application/x-pkcs7-certreqresp", "p7r");
        addMimepPinnt("application/x-pkcs7-crl", "crl");
        addMimepPinnt("application/x-quicktimeplayer", "qtl");
        addMimepPinnt("application/x-shar", "shar");
        addMimepPinnt("application/x-shockwave-flash", "swf");
        addMimepPinnt("application/x-stuffit", "sit");
        addMimepPinnt("application/x-sv4cpio", "sv4cpio");
        addMimepPinnt("application/x-sv4crc", "sv4crc");
        addMimepPinnt("application/x-tar", "tar");
        addMimepPinnt("application/x-texinfo", "texinfo");
        addMimepPinnt("application/x-texinfo", "texi");
        addMimepPinnt("application/x-troff", "t");
        addMimepPinnt("application/x-troff", "roff");
        addMimepPinnt("application/x-troff-man", "man");
        addMimepPinnt("application/x-ustar", "ustar");
        addMimepPinnt("application/x-wais-source", "src");
        addMimepPinnt("application/x-wingz", "wz");
        addMimepPinnt("application/x-webarchive", "webarchive");
        addMimepPinnt("application/x-webarchive-xml", "webarchivexml");
        addMimepPinnt("application/x-x509-ca-cert", "crt");
        addMimepPinnt("application/x-x509-user-cert", "crt");
        addMimepPinnt("application/x-xcf", "xcf");
        addMimepPinnt("application/x-xfig", "fig");
        addMimepPinnt("application/xhtml+xml", "xhtml");
        addMimepPinnt("audio/3gpp", "3gpp");
        addMimepPinnt("audio/amr", "amr");
        addMimepPinnt("audio/basic", "snd");
        addMimepPinnt("audio/midi", "mid");
        addMimepPinnt("audio/midi", "midi");
        addMimepPinnt("audio/midi", "kar");
        addMimepPinnt("audio/midi", "xmf");
        addMimepPinnt("audio/mobile-xmf", "mxmf");
        addMimepPinnt("audio/mpeg", "mpga");
        addMimepPinnt("audio/mpeg", "mpega");
        addMimepPinnt("audio/mpeg", "mp2");
        addMimepPinnt("audio/mpeg", "mp3");
        addMimepPinnt("audio/mpeg", "m4a");
        addMimepPinnt("audio/mpegurl", "m3u");
        addMimepPinnt("audio/prs.sid", "sid");
        addMimepPinnt("audio/x-aiff", "aif");
        addMimepPinnt("audio/x-aiff", "aiff");
        addMimepPinnt("audio/x-aiff", "aifc");
        addMimepPinnt("audio/x-gsm", "gsm");
        addMimepPinnt("audio/x-mpegurl", "m3u");
        addMimepPinnt("audio/x-ms-wma", "wma");
        addMimepPinnt("audio/x-ms-wax", "wax");
        addMimepPinnt("audio/x-pn-realaudio", "ra");
        addMimepPinnt("audio/x-pn-realaudio", "rm");
        addMimepPinnt("audio/x-pn-realaudio", "ram");
        addMimepPinnt("audio/x-realaudio", "ra");
        addMimepPinnt("audio/x-scpls", "pls");
        addMimepPinnt("audio/x-sd2", "sd2");
        addMimepPinnt("audio/x-wav", "wav");
        addMimepPinnt("image/bmp", "bmp");
        addMimepPinnt("audio/x-qcp", "qcp");
        addMimepPinnt("image/gif", "gif");
        addMimepPinnt("image/ico", "cur");
        addMimepPinnt("image/ico", "ico");
        addMimepPinnt("image/ief", "ief");
        addMimepPinnt("image/jpeg", "jpeg");
        addMimepPinnt("image/jpeg", "jpg");
        addMimepPinnt("image/jpeg", "jpe");
        addMimepPinnt("image/pcx", "pcx");
        addMimepPinnt("image/png", "png");
        addMimepPinnt("image/svg+xml", "svg");
        addMimepPinnt("image/svg+xml", "svgz");
        addMimepPinnt("image/tiff", "tiff");
        addMimepPinnt("image/tiff", "tif");
        addMimepPinnt("image/vnd.djvu", "djvu");
        addMimepPinnt("image/vnd.djvu", "djv");
        addMimepPinnt("image/vnd.wap.wbmp", "wbmp");
        addMimepPinnt("image/x-cmu-raster", "ras");
        addMimepPinnt("image/x-coreldraw", "cdr");
        addMimepPinnt("image/x-coreldrawpattern", "pat");
        addMimepPinnt("image/x-coreldrawtemplate", "cdt");
        addMimepPinnt("image/x-corelphotopaint", "cpt");
        addMimepPinnt("image/x-icon", "ico");
        addMimepPinnt("image/x-jg", "art");
        addMimepPinnt("image/x-jng", "jng");
        addMimepPinnt("image/x-ms-bmp", "bmp");
        addMimepPinnt("image/x-photoshop", "psd");
        addMimepPinnt("image/x-portable-anymap", "pnm");
        addMimepPinnt("image/x-portable-bitmap", "pbm");
        addMimepPinnt("image/x-portable-graymap", "pgm");
        addMimepPinnt("image/x-portable-pixmap", "ppm");
        addMimepPinnt("image/x-rgb", "rgb");
        addMimepPinnt("image/x-xbitmap", "xbm");
        addMimepPinnt("image/x-xpixmap", "xpm");
        addMimepPinnt("image/x-xwindowdump", "xwd");
        addMimepPinnt("model/iges", "igs");
        addMimepPinnt("model/iges", "iges");
        addMimepPinnt("model/mesh", "msh");
        addMimepPinnt("model/mesh", "mesh");
        addMimepPinnt("model/mesh", "silo");
        addMimepPinnt("text/calendar", "ics");
        addMimepPinnt("text/calendar", "icz");
        addMimepPinnt("text/comma-separated-values", "csv");
        addMimepPinnt("text/css", "css");
        addMimepPinnt("text/html", "htm");
        addMimepPinnt("text/html", "html");
        addMimepPinnt("text/h323", "323");
        addMimepPinnt("text/iuls", "uls");
        addMimepPinnt("text/mathml", "mml");
        addMimepPinnt("text/plain", "txt");
        addMimepPinnt("text/plain", "asc");
        addMimepPinnt("text/plain", "text");
        addMimepPinnt("text/plain", "diff");
        addMimepPinnt("text/plain", "po");     // vnd.ms的ppt文件
        addMimepPinnt("text/richtext", "rtx");
        addMimepPinnt("text/rtf", "rtf");
        addMimepPinnt("text/texmacs", "ts");
        addMimepPinnt("text/text", "phps");
        addMimepPinnt("text/tab-separated-values", "tsv");
        addMimepPinnt("text/xml", "xml");
        addMimepPinnt("text/x-bibtex", "bib");
        addMimepPinnt("text/x-boo", "boo");
        addMimepPinnt("text/x-c++hdr", "h++");
        addMimepPinnt("text/x-c++hdr", "hpp");
        addMimepPinnt("text/x-c++hdr", "hxx");
        addMimepPinnt("text/x-c++hdr", "hh");
        addMimepPinnt("text/x-c++src", "c++");
        addMimepPinnt("text/x-c++src", "cpp");
        addMimepPinnt("text/x-c++src", "cxx");
        addMimepPinnt("text/x-chdr", "h");
        addMimepPinnt("text/x-component", "htc");
        addMimepPinnt("text/x-csh", "csh");
        addMimepPinnt("text/x-csrc", "c");
        addMimepPinnt("text/x-dsrc", "d");
        addMimepPinnt("text/x-haskell", "hs");
        addMimepPinnt("text/x-java", "java");
        addMimepPinnt("text/x-literate-haskell", "lhs");
        addMimepPinnt("text/x-moc", "moc");
        addMimepPinnt("text/x-pascal", "p");
        addMimepPinnt("text/x-pascal", "pas");
        addMimepPinnt("text/x-pcs-gcd", "gcd");
        addMimepPinnt("text/x-setext", "etx");
        addMimepPinnt("text/x-tcl", "tcl");
        addMimepPinnt("text/x-tex", "tex");
        addMimepPinnt("text/x-tex", "ltx");
        addMimepPinnt("text/x-tex", "sty");
        addMimepPinnt("text/x-tex", "cls");
        addMimepPinnt("text/x-vcalendar", "vcs");
        addMimepPinnt("text/x-vcard", "vcf");
        addMimepPinnt("video/3gpp", "3gpp");
        addMimepPinnt("video/3gpp", "3gp");
        addMimepPinnt("video/3gpp", "3g2");
        addMimepPinnt("video/dl", "dl");
        addMimepPinnt("video/dv", "dif");
        addMimepPinnt("video/dv", "dv");
        addMimepPinnt("video/fli", "fli");
        addMimepPinnt("video/m4v", "m4v");
        addMimepPinnt("video/mpeg", "mpeg");
        addMimepPinnt("video/mpeg", "mpg");
        addMimepPinnt("video/mpeg", "mpe");
        addMimepPinnt("video/mp4", "mp4");
        addMimepPinnt("video/mpeg", "VOB");
        addMimepPinnt("video/quicktime", "qt");
        addMimepPinnt("video/quicktime", "mov");
        addMimepPinnt("video/vnd.mpegurl", "mxu");
        addMimepPinnt("video/webm", "webm");
        addMimepPinnt("video/x-la-asf", "lsf");
        addMimepPinnt("video/x-la-asf", "lsx");
        addMimepPinnt("video/x-mng", "mng");
        addMimepPinnt("video/x-ms-asf", "asf");
        addMimepPinnt("video/x-ms-asf", "asx");
        addMimepPinnt("video/x-ms-wm", "wm");
        addMimepPinnt("video/x-ms-wmv", "wmv");
        addMimepPinnt("video/x-ms-wmx", "wmx");
        addMimepPinnt("video/x-ms-wvx", "wvx");
        addMimepPinnt("video/x-msvideo", "avi");
        addMimepPinnt("video/x-sgi-movie", "movie");
        addMimepPinnt("x-conference/x-cooltalk", "ice");
        addMimepPinnt("x-epoc/x-sisx-app", "sisx"); 
		//自定义部分
		addMimepPinnt("pack/zip", "zip"); 
		addMimepPinnt("pack/tgz", "tgz"); 
		addMimepPinnt("pack/taz", "taz"); 
		addMimepPinnt("pack/gtar", "gtar");
		addMimepPinnt("pack/rar", "rar"); 
		addMimepPinnt("pack/taz", "taz"); 
		addMimepPinnt("pack/apk", "apk"); 
		addMimepPinnt("pack/7z", "7z"); 

		addMimepPinnt("script/sh", "sh"); 
		addMimepPinnt("script/bash", "bash"); 
		addMimepPinnt("script/lua", "lua"); 
		addMimepPinnt("script/js", "js");
	}


}
